
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#  instance:
#    hostname: localhost

server:
  port: 8081
spring:
  application:
    name: client
  rabbitmq:
    addresses: 47.99.134.106:5673
bus: testBus8
