server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
#    register-with-eureka: false
spring:
  application:
    name: eureka1
